name: Download and Upload File

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: "0 6 * * *" # Runs daily at midnight UTC (adjust as needed)

jobs:
  download-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download file
        run: |
          curl -L -o bollettino_utenti.yml "https://meteo.arpa.veneto.it/meteo/bollettini/it/xml/bollettino_utenti.xml"

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Changes
        run: |
          git add downloaded_file.ext
          git commit -m "Updated downloaded_file.ext"
          git push
        continue-on-error: true  # Prevents failure if no changes occur
